# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "dev", "homolog" ]
  pull_request:
    branches: [ "dev", "homolog" ]

jobs:
  build:
    runs-on: ubuntu-latest
    #strategy:
      #matrix:
        #node-version: [14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: "Build images"
      run: docker-compose up -d
      env:
        MARIADB_HOST: ${{ secrets.MARIADB_HOST }}
        MARIADB_USER: ${{ secrets.MARIADB_USER }}
        MARIADB_DATABASE: ${{ secrets.MARIADB_DATABASE }}
        MARIADB_PASS: ${{ secrets.MARIADB_PASS }}
        MARIADB_PORT: ${{ secrets.MARIADB_PORT }}
        MP_URL: ${{ secrets.MP_URL }}
        MP_CLIENT_SECRET: ${{ secrets.MP_CLIENT_SECRET }}
        MP_CLIENT_ID: ${{ secrets.MP_CLIENT_ID }}
        MP_NOTIFICATION_URL: ${{ secrets.MP_NOTIFICATION_URL }}
      
    - name: "Unit Test"
      run: docker-compose exec web npm test
