# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "dev", "homolog" ]
  pull_request:
    branches: [ "dev", "homolog" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: "Construir imagem Docker"
      run: docker-compose up -d
      env:
        MARIADB_HOST: ${{ secrets.MARIADB_HOST }}
        MARIADB_USER: ${{ secrets.MARIADB_USER }}
        MARIADB_DATABASE: ${{ secrets.MARIADB_DATABASE }}
        MARIADB_PASS: ${{ secrets.MARIADB_PASS }}
        MARIADB_PORT: ${{ secrets.MARIADB_PORT }}
        MP_URL: ${{ secrets.MP_URL }}
        MP_CLIENT_SECRET: ${{ secrets.MP_CLIENT_SECRET }}
        MP_CLIENT_ID: ${{ secrets.MP_CLIENT_ID }}
        MP_NOTIFICATION_URL: ${{ secrets.MP_NOTIFICATION_URL }}
  
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Recuperar ID da última imagem
      id: retrieve-image-id
      run: echo "::set-output name=image_id::$(docker images --format "{{.ID}}" | head -n 1)"
      
    - name: Usar imagem Docker
      run: docker run $(echo ${{ steps.retrieve-image-id.outputs.image_id }}) npm test
    #- name: "Unit Test" 
    #  run: docker run docker.io/library/fiaptech_web npm test
